name: Deploy Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_lint_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Linting with Dotnet Format
      run: dotnet format --verify-no-changes --verbosity diagnostic

    - name: Check for warnings with dotnet build
      run: dotnet build --warnaserror --no-restore

    - name: Run the unit tests.
      run: dotnet test Cafeteria.UnitTests/Cafeteria.UnitTests.csproj --no-build

  # integration_test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out the code. 
  #     uses: actions/checkout@v4
  #
  #   - name: Setup .NET 9
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: '9.0.x'
  #
  #   - name: Run the integration tests.
  #     run: dotnet test Cafeteria.IntegrationTests/Cafeteria.IntegrationTests.csproj

  build_and_push_api_to_dockerhub:
    needs: [build_lint_unit_test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push API to DockerHub
      run: |
        docker build \
          -f ./Cafeteria.Api/Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-api:${{ github.run_number }}.${{ github.run_attempt }} \
          .
        docker push -q ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-api:${{ github.run_number }}.${{ github.run_attempt }}

  build_and_push_customer_to_dockerhub:
    needs: [build_lint_unit_test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Customer to DockerHub
      run: |
        docker build \
          -f ./Cafeteria.Customer/Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-customer:${{ github.run_number }}.${{ github.run_attempt }} \
          .
        docker push -q ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-customer:${{ github.run_number }}.${{ github.run_attempt }}

  build_and_push_management_to_dockerhub:
    needs: [build_lint_unit_test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Management to DockerHub
      run: |
        docker build \
          -f ./Cafeteria.Management/Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-management:${{ github.run_number }}.${{ github.run_attempt }} \
          .
        docker push -q ${{ vars.DOCKERHUB_USERNAME }}/cafeteria-management:${{ github.run_number }}.${{ github.run_attempt }}

  # deploy_to_kubernetes:
  #   needs: [build_and_push_api_to_dockerhub, build_and_push_customer_to_dockerhub, build_and_push_management_to_dockerhub]
  #   runs-on: self-hosted
  #   steps:
  #   - name: Check out the code. 
  #     uses: actions/checkout@v4

  #   - name: Deploy to Kubernetes
  #     run: |
  #       export KUBECONFIG=$HOME/.kube/config
  #       kubectl apply -f kube/namespace.yml
  #       export CONTAINER_VERSION=${{ github.run_number }}.${{ github.run_attempt }}
  
  #       for FILE in "kube"/*
  #       do
  #         cat "$FILE" | envsubst | kubectl apply -f -
  #       done

  notify_discord:
    runs-on: ubuntu-latest
    needs: [build_and_push_api_to_dockerhub, build_and_push_customer_to_dockerhub, build_and_push_management_to_dockerhub]
    if: always()
    steps:
    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DEPLOY_MAIN_DISCORD }}
        title: "Snow Cafeteria Portal - Merged Into Main, Deploying"
        description: "Deployment workflow completed"
        url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        status: ${{ job.status }}
