name: Merge Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_lint_unit_test:
    runs-on: ubuntu-slim
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Linting with Dotnet Format
      run: dotnet format --verify-no-changes --verbosity diagnostic

    - name: Check for warnings with dotnet build
      run: dotnet build --warnaserror --no-restore

    - name: Run the unit tests.
      run: dotnet test Cafeteria.UnitTests/Cafeteria.UnitTests.csproj --no-build

  # run_integration_tests:
  #   runs-on: ubuntu-slim
  #   steps:
  #   - name: Check out the code. 
  #     uses: actions/checkout@v4
  #
  #   - name: Setup .NET 9
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: '9.0.x'
  #
  #   - name: Run the integration tests.
  #     run: dotnet test Cafeteria.IntegrationTests/Cafeteria.IntegrationTests.csproj

  notify_discord:
    runs-on: ubuntu-slim
    needs: [build_lint_unit_test]
    if: always()
    steps:
    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.MERGE_DEV_DISCORD }}
        title: "Snow Cafeteria Portal - Merged Into Dev"
        description: "Development workflow completed"
        url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'cancelled') && 'cancelled' || 'success' }}