name: Pull Request Checks

on:
  pull_request:
    types: [created, opened, reopened]
  workflow_dispatch:

jobs:
  build_lint_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Linting with Dotnet Format
      run: dotnet format --verify-no-changes --verbosity diagnostic

    - name: Check for warnings with dotnet build
      run: dotnet build --warnaserror --no-restore

    - name: Run the unit tests.
      run: dotnet test Cafeteria.UnitTests/Cafeteria.UnitTests.csproj --no-build

  # run_integration_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out the code. 
  #     uses: actions/checkout@v4
  #
  #   - name: Setup .NET 9
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: '9.0.x'
  #
  #   - name: Run the integration tests.
  #     run: dotnet test Cafeteria.IntegrationTests/Cafeteria.IntegrationTests.csproj
